# Generated by Django 5.2.6 on 2025-09-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/slider")),
                (
                    "discount_deal",
                    models.CharField(
                        choices=[
                            ("HOT DEALS", "HOT DEALS"),
                            ("New Arraivels", "New Arraivels"),
                            ("New DEALS", "New DEALS"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sale", models.IntegerField()),
                ("brand_name", models.CharField(max_length=100)),
                ("discount", models.IntegerField()),
                ("link", models.CharField(max_length=100)),
            ],
        ),
    ]
