# Generated by Django 5.2.6 on 2025-09-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_slider_discount_deal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner_area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/banner")),
                ("discount_deal", models.CharField(max_length=100)),
                ("qoute", models.CharField(max_length=100)),
                ("discount", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("New Arraivels", "New Arraivels"),
                    ("HOT DEALS", "HOT DEALS"),
                    ("New DEALS", "New DEALS"),
                ],
                max_length=100,
            ),
        ),
    ]
