# Generated by Django 5.2.6 on 2025-09-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_banner_area_alter_slider_discount_deal"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner_area",
            name="link",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("HOT DEALS", "HOT DEALS"),
                    ("New DEALS", "New DEALS"),
                    ("New Arraivels", "New Arraivels"),
                ],
                max_length=100,
            ),
        ),
    ]
