# Generated by Django 5.2.6 on 2025-09-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_maincategory_alter_category_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("New DEALS", "New DEALS"),
                    ("HOT DEALS", "HOT DEALS"),
                    ("New Arraivels", "New Arraivels"),
                ],
                max_length=100,
            ),
        ),
    ]
