# Generated by Django 5.2.6 on 2025-09-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_slider_discount_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("New DEALS", "New DEALS"),
                    ("New Arraivels", "New Arraivels"),
                    ("HOT DEALS", "HOT DEALS"),
                ],
                max_length=100,
            ),
        ),
    ]
