# Generated by Django 5.2.6 on 2025-09-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_slider_discount_deal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("New Arraivels", "New Arraivels"),
                    ("New DEALS", "New DEALS"),
                    ("HOT DEALS", "HOT DEALS"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_quantity", models.IntegerField()),
                ("available_quantity", models.IntegerField()),
                ("featured_image", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("product_information", models.TextField()),
                ("model_name", models.CharField(max_length=100)),
                ("tags", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.category"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.section"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Additional_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specification", models.CharField(max_length=100)),
                ("detail", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_url", models.CharField(max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
            ],
        ),
    ]
