# Generated by Django 5.2.6 on 2025-09-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_section_alter_slider_discount_deal_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_image",
            name="img_url",
        ),
        migrations.AddField(
            model_name="product_image",
            name="images",
            field=models.ImageField(default="", upload_to="media/product/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(upload_to="media/product/"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("HOT DEALS", "HOT DEALS"),
                    ("New Arraivels", "New Arraivels"),
                    ("New DEALS", "New DEALS"),
                ],
                max_length=100,
            ),
        ),
    ]
