# Generated by Django 5.2.6 on 2025-09-08 21:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_product_image_img_url_product_image_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_information",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("HOT DEALS", "HOT DEALS"),
                    ("New DEALS", "New DEALS"),
                    ("New Arraivels", "New Arraivels"),
                ],
                max_length=100,
            ),
        ),
    ]
