# Generated by Django 5.2.6 on 2025-09-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_product_featured_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner_area",
            name="image",
            field=models.ImageField(upload_to="banner"),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(upload_to="product"),
        ),
        migrations.AlterField(
            model_name="product_image",
            name="images",
            field=models.ImageField(default="", upload_to="product"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("HOT DEALS", "HOT DEALS"),
                    ("New DEALS", "New DEALS"),
                    ("New Arraivels", "New Arraivels"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to="slider"),
        ),
    ]
