# Generated by Django 5.2.6 on 2025-09-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_banner_area_image_alter_product_featured_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("New Arraivels", "New Arraivels"),
                    ("New DEALS", "New DEALS"),
                    ("HOT DEALS", "HOT DEALS"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
    ]
