# Generated by Django 5.2.6 on 2025-09-16 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_product_slug_alter_slider_discount_deal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="app.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("HOT DEALS", "HOT DEALS"),
                    ("New DEALS", "New DEALS"),
                    ("New Arraivels", "New Arraivels"),
                ],
                max_length=100,
            ),
        ),
    ]
