# Generated by Django 5.2.6 on 2025-09-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_product_categories_alter_slider_discount_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.category"
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("New DEALS", "New DEALS"),
                    ("HOT DEALS", "HOT DEALS"),
                    ("New Arraivels", "New Arraivels"),
                ],
                max_length=100,
            ),
        ),
    ]
