# Generated by Django 5.2.6 on 2025-09-16 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_slider_discount_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.subcategory"
            ),
        ),
    ]
