# Generated by Django 5.2.6 on 2025-09-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_slider_discount_deal_productreview"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "email")},
        ),
    ]
