# Generated by Django 5.2.6 on 2025-09-25 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_alter_productreview_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productreview",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("New Arraivels", "New Arraivels"),
                    ("HOT DEALS", "HOT DEALS"),
                    ("New DEALS", "New DEALS"),
                ],
                max_length=100,
            ),
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="email",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="name",
        ),
    ]
